<?php

namespace Database\Seeders;

use App\Models\Country;
use Illuminate\Database\Seeder;

class CountrySeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $csvDiverFile = fopen(base_path('database/data/countries.csv'), 'r');

        $firstline = true;

        $countries = [];
        while (($data = fgetcsv($csvDiverFile, 2000, ';')) !== false) {
            if (! $firstline) {

                $countries[] = [
                    'ioc' => $data['0'],
                    'name' => $data['1'],
                    'region_name' => $data['2'],
                    'sub_region_name' => $data['3'],
                    'continent' => $data['4'],
                ];
            }
            $firstline = false;
        }

        Country::insert($countries);

        fclose($csvDiverFile);

        $this->iocToIso();
    }

    private function iocToIso(): void
    {
        $mycountries = Country::all();
        $list = '[
          ["AF","AFG"  ],
          ["AX",""  ],
          ["AL","ALB"  ],
          ["DZ","ALG"  ],
          ["AS","ASA"  ],
          ["AD","AND"  ],
          ["AO","ANG"  ],
          ["AI",""  ],
          ["AQ",""  ],
          ["AG","ANT"  ],
          ["AR","ARG"  ],
          ["AM","ARM"  ],
          ["AW","ARU"  ],
          ["AU","AUS"  ],
          ["AT","AUT"  ],
          ["AZ","AZE"  ],
          ["BS","BAH"  ],
          ["BH","BRN"  ],
          ["BD","BAN"  ],
          ["BB","BAR"  ],
          ["BY","BLR"  ],
          ["BE","BEL"  ],
          ["BZ","BIZ"  ],
          ["BJ","BEN"  ],
          ["BM","BER"  ],
          ["BT","BHU"  ],
          ["BO","BOL"  ],
          ["BA","BIH"  ],
          ["BW","BOT"  ],
          ["BV",""  ],
          ["BR","BRA"  ],
          ["IO",""  ],
          ["VG","IVB"  ],
          ["BN","BRU"  ],
          ["BG","BUL"  ],
          ["BF","BUR"  ],
          ["BI","BDI"  ],
          ["KH","CAM"  ],
          ["CM","CMR"  ],
          ["CA","CAN"  ],
          ["CV","CPV"  ],
          ["BQ",""  ],
          ["KY","CAY"  ],
          ["CF","CAF"  ],
          ["TD","CHA"  ],
          ["CL","CHI"  ],
          ["CN","CHN"  ],
          ["CX",""  ],
          ["CC",""  ],
          ["CO","COL"  ],
          ["KM","COM"  ],
          ["CK","COK"  ],
          ["CR","CRC"  ],
          ["HR","CRO"  ],
          ["CU","CUB"  ],
          ["CW",""  ],
          ["CY","CYP"  ],
          ["CZ","CZE"  ],
          ["CD","COD"  ],
          ["DK","DEN"  ],
          ["DJ","DJI"  ],
          ["DM","DMA"  ],
          ["DO","DOM"  ],
          ["TL","TLS"  ],
          ["EC","ECU"  ],
          ["EG","EGY"  ],
          ["SV","ESA"  ],
          ["GQ","GEQ"  ],
          ["ER","ERI"  ],
          ["EE","EST"  ],
          ["SZ","SWZ"  ],
          ["ET","ETH"  ],
          ["FK",""  ],
          ["FO",""  ],
          ["FM","FSM"  ],
          ["FJ","FIJ"  ],
          ["FI","FIN"  ],
          ["FR","FRA"  ],
          ["GF",""  ],
          ["PF",""  ],
          ["TF",""  ],
          ["GA","GAB"  ],
          ["GM","GAM"  ],
          ["GE","GEO"  ],
          ["DE","GER"  ],
          ["GH","GHA"  ],
          ["GI",""  ],
          ["GR","GRE"  ],
          ["GL",""  ],
          ["GD","GRN"  ],
          ["GP",""  ],
          ["GU","GUM"  ],
          ["GT","GUA"  ],
          ["GG",""  ],
          ["GN","GUI"  ],
          ["GW","GBS"  ],
          ["GY","GUY"  ],
          ["HT","HAI"  ],
          ["HM",""  ],
          ["HN","HON"  ],
          ["HK","HKG"  ],
          ["HU","HUN"  ],
          ["IS","ISL"  ],
          ["IN","IND"  ],
          ["ID","INA"  ],
          ["IR","IRI"  ],
          ["IQ","IRQ"  ],
          ["IE","IRL"  ],
          ["IM",""  ],
          ["IL","ISR"  ],
          ["IT","ITA"  ],
          ["CI","CIV"  ],
          ["JM","JAM"  ],
          ["JP","JPN"  ],
          ["JE",""  ],
          ["JO","JOR"  ],
          ["KZ","KAZ"  ],
          ["KE","KEN"  ],
          ["KI","KIR"  ],
          ["XK","KOS"  ],
          ["KW","KUW"  ],
          ["KG","KGZ"  ],
          ["LA","LAO"  ],
          ["LV","LAT"  ],
          ["LB","LBN"  ],
          ["LS","LES"  ],
          ["LR","LBR"  ],
          ["LY","LBA"  ],
          ["LI","LIE"  ],
          ["LT","LTU"  ],
          ["LU","LUX"  ],
          ["MO",""  ],
          ["MG","MAD"  ],
          ["MW","MAW"  ],
          ["MY","MAS"  ],
          ["MV","MDV"  ],
          ["ML","MLI"  ],
          ["MT","MLT"  ],
          ["MH","MHL"  ],
          ["MQ",""  ],
          ["MR","MTN"  ],
          ["MU","MRI"  ],
          ["YT",""  ],
          ["MX","MEX"  ],
          ["MD","MDA"  ],
          ["MN","MGL"  ],
          ["ME","MNE"  ],
          ["MS",""  ],
          ["MA","MAR"  ],
          ["MZ","MOZ"  ],
          ["MM","MYA"  ],
          ["NA","NAM"  ],
          ["NR","NRU"  ],
          ["NP","NEP"  ],
          ["NL","NED"  ],
          ["NC",""  ],
          ["NZ","NZL"  ],
          ["NI","NCA"  ],
          ["NE","NIG"  ],
          ["NG","NGR"  ],
          ["NU",""  ],
          ["NF",""  ],
          ["KP","PRK"  ],
          ["MK","MKD"  ],
          ["MP",""  ],
          ["NO","NOR"  ],
          ["OM","OMA"  ],
          ["PK","PAK"  ],
          ["PW","PLW"  ],
          ["PS","PLE"  ],
          ["PA","PAN"  ],
          ["PG","PNG"  ],
          ["PY","PAR"  ],
          ["PE","PER"  ],
          ["PH","PHI"  ],
          ["PN",""  ],
          ["PL","POL"  ],
          ["PT","POR"  ],
          ["MC","MON"  ],
          ["PR","PUR"  ],
          ["QA","QAT"  ],
          ["CG","CGO"  ],
          ["RE",""  ],
          ["RO","ROU"  ],
          ["RU","RUS"  ],
          ["RW","RWA"  ],
          ["BL",""  ],
          ["SH",""  ],
          ["KN","SKN"  ],
          ["LC","LCA"  ],
          ["MF",""  ],
          ["PM",""  ],
          ["VC","VIN"  ],
          ["WS","SAM"  ],
          ["SM","SMR"  ],
          ["ST","STP"  ],
          ["SA","KSA"  ],
          ["SN","SEN"  ],
          ["RS","SRB"  ],
          ["SC","SEY"  ],
          ["SL","SLE"  ],
          ["SG","SGP"  ],
          ["SX",""  ],
          ["SK","SVK"  ],
          ["SI","SLO"  ],
          ["SB","SOL"  ],
          ["SO","SOM"  ],
          ["ZA","RSA"  ],
          ["GS",""  ],
          ["KR","KOR"  ],
          ["SS",""  ],
          ["ES","ESP"  ],
          ["LK","SRI"  ],
          ["SD","SUD"  ],
          ["SR","SUR"  ],
          ["SJ",""  ],
          ["SE","SWE"  ],
          ["CH","SUI"  ],
          ["SY","SYR"  ],
          ["TW","TPE"  ],
          ["TJ","TJK"  ],
          ["TZ","TAN"  ],
          ["TH","THA"  ],
          ["TG","TOG"  ],
          ["TK",""  ],
          ["TO","TGA"  ],
          ["TT","TTO"  ],
          ["TN","TUN"  ],
          ["TR","TUR"  ],
          ["TM","TKM"  ],
          ["TC",""  ],
          ["TV","TUV"  ],
          ["UG","UGA"  ],
          ["UA","UKR"  ],
          ["AE","UAE"  ],
          ["GB","GBR"  ],
          ["UM",""  ],
          ["US","USA"  ],
          ["UY","URU"  ],
          ["UZ","UZB"  ],
          ["VU","VAN"  ],
          ["VA",""  ],
          ["VE","VEN"  ],
          ["VN","VIE"  ],
          ["VI","ISV"  ],
          ["WF",""  ],
          ["EH",""  ],
          ["YE","YEM"  ],
          ["ZM","ZAM"  ],
          ["ZW","ZIM"  ]
        ]';

        foreach ($mycountries as $country) {
            foreach (json_decode($list, true) as $v) {
                if ($country->ioc == $v[1]) {
                    $country->iso = $v[0];
                    $country->save();
                }
            }
        }
    }
}
