<?php

namespace Database\Seeders;

use App\Models\Committee;
use Domain\Individuals\Models\ProfessionalRole;
use Domain\Licenses\Models\License;
use Domain\Licenses\Models\LicenseType;
use Illuminate\Database\Seeder;

class LicenseSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        LicenseType::create([
            'name' => 'entity',
        ]);
        LicenseType::create([
            'name' => 'individual',
            'is_individual' => true,
        ]);

        $licenses = [
            [
                'name' => 'Sport Club',
                'committee_id' => Committee::select('id')->where('code', 'SPORT')->pluck('id')->first(),
                'type_id' => 1,
                'unit_value' => 12.99,
                'active' => true,
                'professional_role_id' => null,
                'sport_id' => null,
                'interval' => 1,
                'interval_unit' => 'years',
            ],
            [
                'name' => 'Scientific Diving School',
                'committee_id' => Committee::select('id')->where('code', 'SPORT')->pluck('id')->first(),
                'type_id' => 1,
                'unit_value' => 12.99,
                'active' => true,
                'professional_role_id' => null,
                'sport_id' => null,
                'interval' => 1,
                'interval_unit' => 'years',
            ],
            [
                'name' => 'Scientific Diving Center',
                'committee_id' => Committee::select('id')->where('code', 'SPORT')->pluck('id')->first(),
                'type_id' => 1,
                'unit_value' => 12.99,
                'active' => true,
                'professional_role_id' => null,
                'sport_id' => null,
                'interval' => 1,
                'interval_unit' => 'years',
            ],
            [
                'name' => 'Diving School',
                'committee_id' => Committee::select('id')->where('code', 'SPORT')->pluck('id')->first(),
                'type_id' => 1,
                'professional_role_id' => ProfessionalRole::select('id')->where('code', 'SCIENTIFICDIVER')->pluck('id')->first(),
                'unit_value' => 12.99,
                'active' => true,
                'sport_id' => null,
                'interval' => 1,
                'interval_unit' => 'years',
            ],
            [
                'name' => 'Diving Center',
                'committee_id' => Committee::select('id')->where('code', 'SPORT')->pluck('id')->first(),
                'type_id' => 1,
                'professional_role_id' => ProfessionalRole::select('id')->where('code', 'SCIENTIFICDIVER')->pluck('id')->first(),
                'unit_value' => 14.99,
                'active' => true,
                'sport_id' => null,
                'interval' => 1,
                'interval_unit' => 'years',
            ],
            [
                'name' => 'Diving Instructor',
                'committee_id' => Committee::select('id')->where('code', 'SPORT')->pluck('id')->first(),
                'type_id' => 2,
                'professional_role_id' => ProfessionalRole::select('id')->where('code', 'DIVINGINSTRUCTOR')->pluck('id')->first(),
                'unit_value' => 24.99,
                'active' => true,
                'sport_id' => null,
                'interval' => 1,
                'interval_unit' => 'years',
            ],
            [
                'name' => 'Freediving Instructor',
                'committee_id' => Committee::select('id')->where('code', 'SPORT')->pluck('id')->first(),
                'type_id' => 2,
                'professional_role_id' => ProfessionalRole::select('id')->where('code', 'FREEDIVERINSTRUCTOR')->pluck('id')->first(),
                'unit_value' => 24.99,
                'active' => true,
                'sport_id' => null,
                'interval' => 1,
                'interval_unit' => 'years',
            ],
            [
                'name' => 'Scientific Instructor',
                'committee_id' => Committee::select('id')->where('code', 'SPORT')->pluck('id')->first(),
                'type_id' => 2,
                'professional_role_id' => ProfessionalRole::select('id')->where('code', 'SCIENTIFICINSTRUCTOR')->pluck('id')->first(),
                'unit_value' => 24.99,
                'active' => true,
                'sport_id' => null,
                'interval' => 1,
                'interval_unit' => 'years',
            ],
            [
                'name' => 'Dive Leader',
                'committee_id' => Committee::select('id')->where('code', 'SPORT')->pluck('id')->first(),
                'type_id' => 2,
                'professional_role_id' => ProfessionalRole::select('id')->where('code', 'DIVELEADER')->pluck('id')->first(),
                'unit_value' => 24.99,
                'active' => true,
                'sport_id' => null,
                'interval' => 1,
                'interval_unit' => 'years',
            ],
            [
                'name' => 'Technical Diving Instructor',
                'committee_id' => Committee::select('id')->where('code', 'SPORT')->pluck('id')->first(),
                'type_id' => 2,
                'professional_role_id' => ProfessionalRole::select('id')->where('code', 'TECHNICALDIVINGINSTRUCTOR')->pluck('id')->first(),
                'unit_value' => 24.99,
                'active' => true,
                'sport_id' => null,
                'interval' => 1,
                'interval_unit' => 'years',
            ],
            [
                'name' => 'Finswimming Sport License',
                'committee_id' => Committee::select('id')->where('code', 'SPORT')->pluck('id')->first(),
                'type_id' => 2,
                'unit_value' => 24.99,
                'active' => true,
                'professional_role_id' => ProfessionalRole::select('id')->where('code', 'ATHLETE')->pluck('id')->first(),
                'sport_id' => null,
                'interval' => 1,
                'interval_unit' => 'years',
            ],
            [
                'name' => 'Freediving Sport License',
                'committee_id' => Committee::select('id')->where('code', 'SPORT')->pluck('id')->first(),
                'type_id' => 2,
                'unit_value' => 24.99,
                'active' => true,
                'professional_role_id' => ProfessionalRole::select('id')->where('code', 'ATHLETE')->pluck('id')->first(),
                'sport_id' => null,
                'interval' => 1,
                'interval_unit' => 'years',
            ],
            [
                'name' => 'Aquathlon Sport License',
                'committee_id' => Committee::select('id')->where('code', 'SPORT')->pluck('id')->first(),
                'type_id' => 2,
                'unit_value' => 24.99,
                'active' => true,
                'professional_role_id' => ProfessionalRole::select('id')->where('code', 'ATHLETE')->pluck('id')->first(),
                'sport_id' => null,
                'interval' => 1,
                'interval_unit' => 'years',
            ],
            [
                'name' => 'Underwater Hockey Sport License',
                'committee_id' => Committee::select('id')->where('code', 'SPORT')->pluck('id')->first(),
                'type_id' => 2,
                'unit_value' => 24.99,
                'active' => true,
                'professional_role_id' => ProfessionalRole::select('id')->where('code', 'ATHLETE')->pluck('id')->first(),
                'sport_id' => null,
                'interval' => 1,
                'interval_unit' => 'years',
            ],
            [
                'name' => 'Underwater Rugby Sport License',
                'committee_id' => Committee::select('id')->where('code', 'SPORT')->pluck('id')->first(),
                'type_id' => 2,
                'unit_value' => 24.99,
                'active' => true,
                'professional_role_id' => ProfessionalRole::select('id')->where('code', 'ATHLETE')->pluck('id')->first(),
                'sport_id' => null,
                'interval' => 1,
                'interval_unit' => 'years',
            ],
            [
                'name' => 'Target Shooting Sport License',
                'committee_id' => Committee::select('id')->where('code', 'SPORT')->pluck('id')->first(),
                'type_id' => 2,
                'unit_value' => 24.99,
                'active' => true,
                'professional_role_id' => ProfessionalRole::select('id')->where('code', 'ATHLETE')->pluck('id')->first(),
                'sport_id' => null,
                'interval' => 1,
                'interval_unit' => 'years',
            ],
            [
                'name' => 'Sport Diving Sport License',
                'committee_id' => Committee::select('id')->where('code', 'SPORT')->pluck('id')->first(),
                'type_id' => 2,
                'unit_value' => 24.99,
                'active' => true,
                'professional_role_id' => ProfessionalRole::select('id')->where('code', 'ATHLETE')->pluck('id')->first(),
                'sport_id' => null,
                'interval' => 1,
                'interval_unit' => 'years',
            ],
            [
                'name' => 'Spearfishing Sport License',
                'committee_id' => Committee::select('id')->where('code', 'SPORT')->pluck('id')->first(),
                'type_id' => 2,
                'unit_value' => 24.99,
                'active' => true,
                'professional_role_id' => ProfessionalRole::select('id')->where('code', 'ATHLETE')->pluck('id')->first(),
                'sport_id' => null,
                'interval' => 1,
                'interval_unit' => 'years',
            ],
            [
                'name' => 'Orienteering Sport License',
                'committee_id' => Committee::select('id')->where('code', 'SPORT')->pluck('id')->first(),
                'type_id' => 2,
                'unit_value' => 24.99,
                'active' => true,
                'professional_role_id' => ProfessionalRole::select('id')->where('code', 'ATHLETE')->pluck('id')->first(),
                'sport_id' => null,
                'interval' => 1,
                'interval_unit' => 'years',
            ],
            [
                'name' => 'Visual Sport License',
                'committee_id' => Committee::select('id')->where('code', 'SPORT')->pluck('id')->first(),
                'type_id' => 2,
                'unit_value' => 24.99,
                'active' => true,
                'professional_role_id' => ProfessionalRole::select('id')->where('code', 'ATHLETE')->pluck('id')->first(),
                'sport_id' => null,
                'interval' => 1,
                'interval_unit' => 'years',
            ],
            [
                'name' => 'Freediving Judge License',
                'committee_id' => Committee::select('id')->where('code', 'SPORT')->pluck('id')->first(),
                'type_id' => 2,
                'unit_value' => 24.99,
                'active' => true,
                'professional_role_id' => null,
                'sport_id' => null,
                'interval' => 1,
                'interval_unit' => 'years',
            ],
            [
                'name' => 'Aquathlon Judge License',
                'committee_id' => Committee::select('id')->where('code', 'SPORT')->pluck('id')->first(),
                'type_id' => 2,
                'unit_value' => 24.99,
                'active' => true,
                'professional_role_id' => null,
                'sport_id' => null,
                'interval' => 1,
                'interval_unit' => 'years',
            ],
            [
                'name' => 'Underwater Hockey Referee License',
                'committee_id' => Committee::select('id')->where('code', 'SPORT')->pluck('id')->first(),
                'type_id' => 2,
                'unit_value' => 24.99,
                'active' => true,
                'professional_role_id' => null,
                'sport_id' => null,
                'interval' => 1,
                'interval_unit' => 'years',
            ],
            [
                'name' => 'Underwater Rugby Referee License',
                'committee_id' => Committee::select('id')->where('code', 'SPORT')->pluck('id')->first(),
                'type_id' => 2,
                'unit_value' => 24.99,
                'active' => true,
                'professional_role_id' => null,
                'sport_id' => null,
                'interval' => 1,
                'interval_unit' => 'years',
            ],
            [
                'name' => 'Target Shooting Judge License',
                'committee_id' => Committee::select('id')->where('code', 'SPORT')->pluck('id')->first(),
                'type_id' => 2,
                'unit_value' => 24.99,
                'active' => true,
                'professional_role_id' => ProfessionalRole::select('id')->where('code', 'TARGETSHOOTINGJUDGE')->pluck('id')->first(),
                'sport_id' => null,
                'interval' => 1,
                'interval_unit' => 'years',
            ],
            [
                'name' => 'Sport Diving Judge License',
                'committee_id' => Committee::select('id')->where('code', 'SPORT')->pluck('id')->first(),
                'type_id' => 2,
                'unit_value' => 24.99,
                'active' => true,
                'professional_role_id' => ProfessionalRole::select('id')->where('code', 'SPORTDIVINGJUDGE')->pluck('id')->first(),
                'sport_id' => null,
                'interval' => 1,
                'interval_unit' => 'years',
            ],
            [
                'name' => 'Spearfishing Judge License',
                'committee_id' => Committee::select('id')->where('code', 'SPORT')->pluck('id')->first(),
                'type_id' => 2,
                'unit_value' => 24.99,
                'active' => true,
                'professional_role_id' => ProfessionalRole::select('id')->where('code', 'SPEARFISHINGJUDGE')->pluck('id')->first(),
                'sport_id' => null,
                'interval' => 1,
                'interval_unit' => 'years',
            ],
            [
                'name' => 'Orienteering Judge License',
                'committee_id' => Committee::select('id')->where('code', 'SPORT')->pluck('id')->first(),
                'type_id' => 2,
                'unit_value' => 24.99,
                'active' => true,
                'professional_role_id' => ProfessionalRole::select('id')->where('code', 'ORIENTEERINGREFEREE')->pluck('id')->first(),
                'sport_id' => null,
                'interval' => 1,
                'interval_unit' => 'years',
            ],
            [
                'name' => 'Visual Judge License',
                'committee_id' => Committee::select('id')->where('code', 'SPORT')->pluck('id')->first(),
                'type_id' => 2,
                'unit_value' => 24.99,
                'active' => true,
                'professional_role_id' => ProfessionalRole::select('id')->where('code', 'VISUALJURY')->pluck('id')->first(),
                'sport_id' => null,
                'interval' => 1,
                'interval_unit' => 'years',
            ],
            [
                'name' => 'Freediving Coach License',
                'committee_id' => Committee::select('id')->where('code', 'SPORT')->pluck('id')->first(),
                'type_id' => 2,
                'unit_value' => 24.99,
                'active' => true,
                'professional_role_id' => ProfessionalRole::select('id')->where('code', 'FREEDIVINGCOACH')->pluck('id')->first(),
                'sport_id' => null,
                'interval' => 1,
                'interval_unit' => 'years',
            ],
            [
                'name' => 'Aquathlon Coach License',
                'committee_id' => Committee::select('id')->where('code', 'SPORT')->pluck('id')->first(),
                'type_id' => 2,
                'unit_value' => 24.99,
                'active' => true,
                'professional_role_id' => ProfessionalRole::select('id')->where('code', 'AQUATHLONCOACH')->pluck('id')->first(),
                'sport_id' => null,
                'interval' => 1,
                'interval_unit' => 'years',
            ],
            [
                'name' => 'Underwater Hockey Coach License',
                'committee_id' => Committee::select('id')->where('code', 'SPORT')->pluck('id')->first(),
                'type_id' => 2,
                'unit_value' => 24.99,
                'active' => true,
                'professional_role_id' => ProfessionalRole::select('id')->where('code', 'UNDERWATERHOCKEYCOACH')->pluck('id')->first(),
                'sport_id' => null,
                'interval' => 1,
                'interval_unit' => 'years',
            ],
            [
                'name' => 'Underwater Rugby Coach License',
                'committee_id' => Committee::select('id')->where('code', 'SPORT')->pluck('id')->first(),
                'type_id' => 2,
                'unit_value' => 24.99,
                'active' => true,
                'professional_role_id' => ProfessionalRole::select('id')->where('code', 'UNDERWATERRUGBYCOACH')->pluck('id')->first(),
                'sport_id' => null,
                'interval' => 1,
                'interval_unit' => 'years',
            ],
            [
                'name' => 'Target Shooting Coach License',
                'committee_id' => Committee::select('id')->where('code', 'SPORT')->pluck('id')->first(),
                'type_id' => 2,
                'unit_value' => 24.99,
                'active' => true,
                'professional_role_id' => ProfessionalRole::select('id')->where('code', 'TARGETSHOOTINGCOACH')->pluck('id')->first(),
                'sport_id' => null,
                'interval' => 1,
                'interval_unit' => 'years',
            ],
            [
                'name' => 'Sport Diving Coach License',
                'committee_id' => Committee::select('id')->where('code', 'SPORT')->pluck('id')->first(),
                'type_id' => 2,
                'unit_value' => 24.99,
                'active' => true,
                'professional_role_id' => ProfessionalRole::select('id')->where('code', 'SPORTDIVINGCOACH')->pluck('id')->first(),
                'sport_id' => null,
                'interval' => 1,
                'interval_unit' => 'years',
            ],
            [
                'name' => 'Spearfishing Coach License',
                'committee_id' => Committee::select('id')->where('code', 'SPORT')->pluck('id')->first(),
                'type_id' => 2,
                'unit_value' => 24.99,
                'active' => true,
                'professional_role_id' => ProfessionalRole::select('id')->where('code', 'SPEARFISHINGCOACH')->pluck('id')->first(),
                'sport_id' => null,
                'interval' => 1,
                'interval_unit' => 'years',
            ],
            [
                'name' => 'Orienteering Coach License',
                'committee_id' => Committee::select('id')->where('code', 'SPORT')->pluck('id')->first(),
                'type_id' => 2,
                'unit_value' => 24.99,
                'active' => true,
                'professional_role_id' => ProfessionalRole::select('id')->where('code', 'ORIENTEERINGCOACH')->pluck('id')->first(),
                'sport_id' => null,
                'interval' => 1,
                'interval_unit' => 'years',
            ],
            [
                'name' => 'Visual Coach License',
                'committee_id' => Committee::select('id')->where('code', 'SPORT')->pluck('id')->first(),
                'type_id' => 2,
                'unit_value' => 24.99,
                'active' => true,
                'professional_role_id' => ProfessionalRole::select('id')->where('code', 'VISUALCOACH')->pluck('id')->first(),
                'sport_id' => null,
                'interval' => 1,
                'interval_unit' => 'years',
            ],
        ];

        License::insert($licenses);
    }
}
