<?php

return [
    'title' => 'Reports',
    'generate_new' => 'Generate a new report',
    'generate_description' => 'You can create a new report by selecting the report type and clicking on the generate button. Or choose from an already generated report below.',
    'report_type' => 'Report Type',
    'start_date' => 'Start Date',
    'end_date' => 'End Date',
    'generate_report' => 'Generate Report',
    'generating' => 'Generating...',
    'generating_report' => 'Generating report... This may take a few seconds.',

    // Table headers
    'table' => [
        'report_type' => 'Report Type',
        'generated_by' => 'Generated By',
        'date_generated' => 'Date Generated',
        'date_range' => 'Date Range',
        'size' => 'Size',
        'status' => 'Status',
        'actions' => 'Actions',
    ],

    // Date range
    'all_time' => 'All time',
    'present' => 'Present',
    'no_date_range' => 'No date range',

    // Actions
    'download_report' => 'Download Report',
    'delete_report' => 'Delete Report',

    // Status
    'status' => [
        'ready' => 'Ready',
        'processing' => 'Processing',
        'failed' => 'Failed',
    ],

    // Report display names
    'individual_insurances_list' => 'Administrative - Individual Insurances',
    'entity_insurances_list' => 'Administrative - Entity Insurances',
    'affiliations_list' => 'Administrative - Entity and Individual Affiliations',
    'entities_list' => 'Administrative - Entities List',
    'coaches_list' => 'Sport - Coaches',
    'technical_officials_list' => 'Sport - Technical Officials',
    'cmas_diving_certifications_list' => 'International - Diving Certifications',
    'athletes_list' => 'Sport - Athletes',
    'cmas_scientific_certifications_list' => 'International - Scientific Certifications',

    // Column headers
    'columns' => [
        'entity' => 'Entity',
        'entity_name' => 'Entity Name',
        'legal_name' => 'Legal Name',
        'member' => 'Member',
        'member_number' => 'Member Number',
        'member_id' => 'ID Number',
        'federation' => 'Federation',
        'territorial_association' => 'Territorial Association',
        'sport_association' => 'Sport Association',
        'responsible_person' => 'Responsible Person',
        'vat_number' => 'VAT Number',
        'country' => 'Country',
        'district' => 'District',
        'zone' => 'Zone',
        'address' => 'Address',
        'locality' => 'Locality',
        'postal_code' => 'Postal Code',
        'email' => 'Email',
        'phone' => 'Phone',
        'website' => 'Website',
        'facebook' => 'Facebook',
        'x' => 'X',
        'instagram' => 'Instagram',
        'linkedin' => 'LinkedIn',
        'cmas_portal' => 'International Portal Account',
        'affiliation_status' => 'Affiliation Status',
        'activation_date' => 'Activation Date',
        'birth_date' => 'Birth Date',
        'age_category' => 'Age Category',
        'requested_by' => 'Requested by',
        'insurance_plan' => 'Insurance Plan',
        'full_name' => 'Full Name',
        'certification_name' => 'Certification Name',
        'certification_number' => 'Certification Number',
        'issue_date' => 'Issue Date',
        'expiry_date' => 'Expiry Date',
        'certification_status' => 'Certification Status',
        'gender' => 'Gender',
        'course_director' => 'Course Director',
        'school' => 'School',
        'license_name' => 'License Name',
        'license_number' => 'License Number',
        'status' => 'Status',
    ],

    // Age categories
    'age_categories' => [
        'child' => 'Child',
        'youth' => 'Youth',
        'senior' => 'Senior',
        'master' => 'Master',
    ],

    // Insurer status
    'insurer_status' => 'Insurer',
    'insurer_statuses' => [
        'pending' => 'To Send',
        'sent' => 'Sent',
        'completed' => 'Completed',
    ],

    // Insurance Reports page
    'insurance_reports_title' => 'Insurance Reports',
    'insurance_report_description' => 'Generate and manage Insurance reports for Individuals and Entities. Select the type and date range, then generate. A weekly report is automatically generated every Sunday.',
    'system_generated' => 'System (automatic)',
    'generation_failed' => 'Report generation failed. Please try again.',
    'confirm_delete_report' => 'Are you sure you want to delete this report?',

    // General
    'not_available' => 'N/A',
    'yes' => 'Yes',
    'no' => 'No',
];
