<?php

namespace App\Http\Requests;

use Illuminate\Foundation\Http\FormRequest;

/**
 * Form request for creating entities from the federation context.
 *
 * This differs from EntityCreateRequest in that:
 * - Password is auto-generated by the controller (not required from user)
 * - Entity types are not required (federation determines the type)
 * - District is optional (uses Livewire component with optional selection)
 */
class FederationEntityCreateRequest extends FormRequest
{
    /**
     * Determine if the user is authorized to make this request.
     */
    public function authorize(): bool
    {
        return true;
    }

    /**
     * Get the validation rules that apply to the request.
     *
     * @return array<string, mixed>
     */
    public function rules(): array
    {
        return [
            'federation_id' => 'sometimes',
            'name' => 'required|string|max:191',
            'legal_name' => 'required|string|max:100',
            'legal_responsible_person' => 'nullable|string|max:100',
            'vat_number' => 'nullable|string|max:20',
            'address' => 'nullable|string|max:191',
            'location' => 'nullable|string',
            'postal_code' => 'nullable|string|max:20',
            'lat' => 'nullable|numeric',
            'lng' => 'nullable|numeric',
            'email' => 'nullable|email|max:100',
            'website' => 'nullable|string|max:191',
            'phone' => 'nullable|string|max:20',
            'user_email' => 'required|email|unique:users,email',
            'logo' => 'nullable|image',
            'terms' => 'accepted',
            'data_sharing' => 'accepted',
            'national_federation_number' => 'nullable|string',
            'facebook_url' => 'nullable|url:http,https',
            'x_url' => 'nullable|url:http,https',
            'instagram_url' => 'nullable|url:http,https',
            'linkedin_url' => 'nullable|url:http,https',
            'district_id' => 'nullable|integer|exists:districts,id',
            'country_id' => 'nullable|integer|exists:country,id',
            // Zone assignment
            'zone_ids' => 'nullable|array',
            'zone_ids.*' => 'nullable|integer|exists:zones,id',
            // Entity types are optional for federation flow
            'entity_types' => 'nullable|array',
            'entity_types.*' => 'nullable|string|in:sport,diving',
        ];
    }
}
