<?php

use App\Models\Country;
use Domain\Entities\Actions\CreateEntityAction;
use Domain\Entities\Actions\EditEntityAction;
use Domain\Entities\DataTransferObject\EntityData;
use Domain\Entities\Models\Entity;
use Domain\Federations\Models\Federation;
use Illuminate\Foundation\Testing\RefreshDatabase;
use Illuminate\Support\Facades\Queue;

use function Pest\Laravel\artisan;

uses(RefreshDatabase::class);

beforeEach(function () {
    Queue::fake([\App\Jobs\GenerateModelQrCode::class]);

    artisan('db:seed --class=RoleAndPermissionSeeder');

    $this->country = Country::factory()->create();
    $this->defaultFederation = Federation::factory()->state(['is_default_federation' => true])->create();
});

it('associates entity with default federation when no federation is specified', function () {

    $entityData = new EntityData(
        federation_id: null,
        committee_id: null,
        country_id: $this->country->id,
        vat_number: '123456789',
        name: 'Test Entity',
        legal_name: 'Test Entity Legal Name',
        legal_responsible_person: 'John Doe',
        phone: '1234567890',
        email: 'testentity@example.com',
        member_code: null,
        website: 'https://entity.example.test',
        address: '123 Test Street',
        postal_code: '2560-331',
        location: 'Test City',
        lat: 12.34,
        lng: 56.78,
        logo: null,
        national_federation_number: null,
        qrcode_path: null
    );

    $createEntityAction = new CreateEntityAction;
    $entity = $createEntityAction($entityData);

    // Assert the entity is created
    expect($entity)->toBeInstanceOf(Entity::class);
    expect($entity->federations)->toHaveCount(1);
    expect($entity->entityFederations)->toHaveCount(1);

    // Assert the entity is associated with the default federation
    $federationIds = $entity->federations->pluck('id')->toArray();
    expect($federationIds)->toContain($this->defaultFederation->id);
});

it('does not clear member_code and qrcode_path when updating an entity', function () {
    // 1. Create an entity with a member_code using the factory
    $initialMemberCode = 'CMAS_CO';
    /** @var Entity $entity */
    $entity = Entity::factory()->create([
        'country_id' => $this->country->id,
        'member_code' => $initialMemberCode,
        'name' => 'Original Name For Update Test',
        // 'federation_id' => $this->defaultFederation->id, // This was causing the error
    ]);

    // Attach the federation after creating the entity
    $entity->federations()->attach($this->defaultFederation->id);

    // The HasQrCode trait should have run on create, setting the qrcode_path.
    // Refresh to get DB generated values like qrcode_path and load the relationship.
    $entity->refresh();

    // Manually set a dummy qrcode_path to simulate it being generated by the async job
    // and to test if the update action preserves it.
    $expectedQrCodePath = 'test/qrcodes/entity_cmas123.png';
    $entity->qrcode_path = $expectedQrCodePath;
    $entity->save(); // Save the manually set path
    $entity->refresh(); // Ensure it's reloaded from DB

    expect($entity->member_code)->toBe($initialMemberCode);
    // Check that our manually set qrcode_path is now on the model
    expect($entity->qrcode_path)->toBe($expectedQrCodePath);
    $originalQrCodePath = $entity->qrcode_path; // Store this known path

    // 2. Prepare update data (e.g., change name, but DTO will have qrcode_path as null)
    $updatedName = 'Updated Entity Name Test';
    $updateDto = new EntityData(
        federation_id: $entity->federations->pluck('id')->toArray(),
        committee_id: null,
        country_id: $entity->country_id,
        vat_number: $entity->vat_number,
        name: $updatedName, // Changed field
        legal_name: $entity->legal_name,
        legal_responsible_person: $entity->legal_responsible_person,
        phone: $entity->phone,
        email: $entity->email,
        member_code: $entity->member_code,
        website: $entity->website,
        address: $entity->address,
        postal_code: $entity->postal_code,
        location: $entity->location,
        lat: $entity->lat,
        lng: $entity->lng,
        logo: null,
        national_federation_number: $entity->getNationalFederationNumber(), // Method on Entity model
        qrcode_path: null, // Explicitly null in DTO, simulating it not coming from a form
        public_description: $entity->public_description,
        facebook_url: $entity->facebook_url,
        x_url: $entity->x_url,
        instagram_url: $entity->instagram_url,
        linkedin_url: $entity->linkedin_url
    );

    // 3. Execute EditEntityAction
    $editEntityAction = new EditEntityAction;
    $editEntityAction($updateDto, $entity->id);

    // 4. Retrieve the updated entity
    $updatedEntity = Entity::find($entity->id);
    expect($updatedEntity)->not->toBeNull();

    // 5. Assertions
    expect($updatedEntity->name)->toBe($updatedName);
    expect($updatedEntity->member_code)->toBe($initialMemberCode); // Should NOT have changed
    expect($updatedEntity->qrcode_path)->toBe($originalQrCodePath); // Should NOT have changed
});
