<x-layout>
    <livewire:attachments.attachment-create
        :committee="$committee"
        :countries="$countries"
        :categories="$categories"
        :professional_roles="$professional_roles"
        :licenses="$licenses"
        :entity_licenses="$entity_licenses"
        :individual_licenses="$individual_licenses"
        :federations="$federations"
        :certifications="$certifications"
        :languages="$languages"
        />
</x-layout>
