<div class="isolate">
    {{-- Instructions Card --}}
    <div class="card mb-6 z-20">
        <h2 class="text-lg font-semibold mb-2">
            @if ($actorType === 'entity')
                {{ __('certifications.step_1_context_entity') }}
            @else
                {{ __('certifications.step_1_context') }}
            @endif
        </h2>
        @if ($actorType === 'federation')
            <p class="text-sm text-gray-600 mb-4">
                @if ($committee_code === 'sport')
                    {{ __('certifications.select_school_and_director_federation') }}
                @else
                    {{ __('certifications.select_school_and_director_ntc') }}
                @endif
            </p>
        @endif
        {{-- Instructions box (kept inside the card) --}}
        <div class="border-2 border-blue-300 bg-blue-50 rounded-lg p-4">
            <div class="flex">
                <div class="flex-shrink-0">
                    <svg xmlns="http://www.w3.org/2000/svg" class="h-6 w-6 text-blue-500" fill="none"
                        viewBox="0 0 24 24" stroke="currentColor">
                        <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2"
                            d="M13 16h-1v-4h-1m1-4h.01M21 12a9 9 0 11-18 0 9 9 0 0118 0z" />
                    </svg>
                </div>
                <div class="ml-3">
                    <h3 class="text-sm font-medium text-blue-800">{{ __('certifications.instructions') }}</h3>
                    <div class="mt-2 text-sm text-gray-600">
                        @if ($actorType === 'entity')
                            <ul class="list-disc pl-5 mt-1 space-y-1">
                                <li>{{ __('certifications.entity_instruction_1') }}</li>
                                <li>{{ __('certifications.entity_instruction_2') }}</li>
                                <li>{{ __('certifications.entity_instruction_3') }}</li>
                                <li>{{ __('certifications.entity_instruction_4') }}</li>
                            </ul>
                        @else
                            <p>{{ __('certifications.please_provide_details') }}</p>
                            <ul class="list-disc pl-5 mt-1 space-y-1">
                                @if ($committee_code !== 'sport')
                                    <li>{{ __('certifications.optionally_select_school') }}</li>
                                @endif
                                <li>{{ __('certifications.select_director_or_check') }}</li>
                            </ul>
                        @endif
                    </div>
                </div>
            </div>
        </div>
    </div>

    {{-- School Selection & Federation Approval Card (Now part of Filament form schema) --}}
    {{-- The actual form fields (School select, FederationApprove checkbox) are now generated by Filament --}}
    {{-- based on getStep1FormSchema() in the Livewire component. --}}
    {{-- We only render the form here if it's a federation actor, as entities have no form fields in step 1. --}}
    @if ($actorType === 'federation')
    <form wire:submit.prevent="nextStep">
        {{ $this->form }}
        {{-- This will render fields defined in getStep1FormSchema for the current step --}}
    </form>
    @endif

    {{-- Director Selection Card --}}
    @if (!($actorType === 'federation' && $federationApprove))
    <div class="card mt-6">
        <div class="flex justify-between items-center mb-4">
            <h2 class="text-lg font-semibold">
                @if ($actorType === 'federation')
                    {{ __('certifications.course_director_optional') }}
                @else
                    {{ __('certifications.course_director') }}
                @endif
            </h2>
            @if ($selectedDirector)
                <button type="button" wire:click="removeDirector" class="text-sm text-red-500 hover:text-red-700">
                    {{ __('certifications.remove_director') }}
                </button>
            @endif
        </div>

        @if ($selectedDirector)
            <x-certifications.wizard.summary-card :title="__('certifications.selected_director')" :individual="$selectedDirector" />
        @else
            <livewire:certifications.wizard.director-selector-table :selectedFederationId="$selectedFederationId" :selectedSchoolId="$selectedSchoolId"
                :committee_code="$committee_code" :actorType="$actorType" {{-- Pass actorType to the selector if it needs different logic --}} />
            @error('selectedDirectorId')
                <span class="text-xs text-danger-500 mt-1">{{ $message }}</span>
            @enderror
            @error('step1_requirement')
                <span class="text-xs text-danger-500 mt-1">{{ $message }}</span>
            @enderror
        @endif
    </div>
    @endif

    {{-- Assistant Selection Accordion --}}
    @if (!($actorType === 'federation' && $federationApprove))
    <div x-data="{ isOpen: false }" class="border rounded-lg overflow-hidden mt-6">
        {{-- Accordion Header --}}
        <button @click="isOpen = !isOpen" type="button"
            class="flex justify-between items-center w-full p-4 bg-slate-200 text-slate-800 hover:bg-slate-100">
            <div class="text-left">
                <h3 class="font-medium text-lg ">{{ __('certifications.assistant_instructors') }}</h3>
                <span class="text-xs text-slate-800">
                    {{ $selectedAssistants->count() }} {{ __('certifications.selected') }}
                </span>
            </div>
            <x-icon name="heroicon-o-chevron-down"
                class="w-5 h-5 text-gray-400 transform transition-transform duration-200"
                x-bind:class="{ '-rotate-180': isOpen }" />
        </button>
        {{-- Accordion Content --}}
        <div x-show="isOpen" x-collapse class="p-4 border-t bg-slate-100">
            {{-- Display selected assistants as chips/cards --}}
            <div class="flex flex-wrap gap-1 mb-2">
                @forelse($selectedAssistants as $assistant)
                    <span
                        class="inline-flex items-center px-2 py-0.5 rounded text-xs font-medium bg-green-100 text-green-800">
                        {{ $assistant->full_name }}
                        <button type="button" wire:click="toggleAssistant({{ $assistant->id }})"
                            title="{{ __('certifications.remove_assistant') }}" class="ml-1 text-green-600 hover:text-green-800">
                            <x-icon name="heroicon-o-x-mark" class="w-3 h-3" />
                        </button>
                    </span>
                @empty
                    <p class="text-xs text-gray-500 italic w-full">{{ __('certifications.no_assistants_selected') }}</p>
                @endforelse
            </div>
            <livewire:certifications.wizard.assistant-selector-table :selected-school-id="$selectedSchoolId" :selected-federation-id="$selectedFederationId"
                :selected-director-id="$selectedDirectorId" :selected-assistant-ids="$selectedAssistantIds"
                :committee_code="$committee_code"
                wire:key="assistant-selector-{{ $selectedSchoolId ?? 'x' }}-{{ $selectedDirectorId ?? 'x' }}-{{ is_array($selectedAssistantIds) && count($selectedAssistantIds) ? implode('-', $selectedAssistantIds) : 'none' }}" />
        </div>
    </div>
    @endif
</div>
